In [1]:
import numpy as np
import pprint
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

In [2]:
pp = pprint.PrettyPrinter(indent=2)
env = GridworldEnv()

In [29]:
def value_iteration(env, theta=0.0001, discount_factor=1.0):
    """
    Value Iteration Algorithm.
    
    Args:
        env: OpenAI environment. env.P represents the transition probabilities of the environment.
        theta: Stopping threshold. If the value of all states changes less than theta
            in one iteration we are done.
        discount_factor: lambda time discount factor.
        
    Returns:
        A tuple (policy, V) of the optimal policy and the optimal value function.        
    """
    

    V = np.zeros(env.nS)
    policy = np.zeros([env.nS, env.nA])
    Vnew = np.zeros(env.nS)
    policy_new=np.zeros([env.nS, env.nA])
    # Implement!
    while True:
        # TODO: Implement!
        for i in range (env.nS): 
            q_values=[]
            for j in range(0,4):
                prob, next_state, reward,_= env.P[i][j][0]
                q_value=0
                for k in range (len(env.P[i][j])):
                    prob, next_state, reward,_=env.P[i][j][k]
                    q_value+=reward+discount_factor * V[next_state]*prob
                q_values.append(q_value)    
            idx = np.argmax(q_values) 
            Vnew[i]=q_values[idx]
            policy_new[i],policy_new[i,idx]=0,1
        if np.array_equal(policy_new,policy):

            break
        print "ok"
        V=Vnew.copy()
        policy=policy_new.copy()

 
    return policy, V

In [30]:
policy, v = value_iteration(env)

print("Policy Probability Distribution:")
print(policy)
print("")

print("Reshaped Grid Policy (0=up, 1=right, 2=down, 3=left):")
print(np.reshape(np.argmax(policy, axis=1), env.shape))
print("")

print("Value Function:")
print(v)
print("")

print("Reshaped Grid Value Function:")
print(v.reshape(env.shape))
print("")

[0.0, 0.0, 0.0, 0.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[-1.0, -1.0, -1.0, -1.0]
0
[0.0, 0.0, 0.0, 0.0]
0
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]] [[ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.

In [31]:
# Test the value function
expected_v = np.array([ 0, -1, -2, -3, -1, -2, -3, -2, -2, -3, -2, -1, -3, -2, -1,  0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)